---
abstract: 'A type-constraint-to-data map'
author:
  - '=over 4'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.95'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-TypeMap
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 1.02
  MooseX::Types: 0.19
  namespace::clean: 0
resources:
  IRC: irc://irc.perl.org/#moose
  license: http://dev.perl.org/licenses/
  repository: git://github.com/groditi/MooseX-TypeMap.git
version: 0.003000
